Hotfix/login api
dayum-diet/dayum-diet-backend pull request #11
Opened 2024-11-29 01:06 UTC by sungryongcho

2024-11-29 13:21 UTC, Daeho-Son commented
Dto 파일을 보면 Builder 클래스를 새로 만들어서 사용하셨는데 이렇게 하신 이유가 궁금합니다.

생성자를 추가하고 `@Builder`를 추가해서 사용하지 않은 이유가 뭔가요?

2024-11-29 13:30 UTC, Daeho-Son commented
`/token`을 도메인으로 따로 두신 이유가 궁금합니다.

TokenProvider.java는 사실상 jwt을 편리하게 사용하기 위한 메서드를 모아놓은 거라고 생각합니다. 그렇기 때문에 `/jwt`로 이동하는게 맞는 거 같습니다.

TokenService.java는 이름과 다르게 캐시에 관련된 기능을 수행하고 있습니다. CacheService.java 혹은 CacheUtil.java가 더 잘 어울리는 것 같습니다.

2024-11-29 13:36 UTC, Daeho-Son requested changes
코드 작성하시느라 고생하셨습니다. 3개의 리뷰 외에도 이전에 추가한 부분은 리뷰로 작성이 안돼서 코멘트로 작성했습니다.

확인하시고 이해가 안되는 부분이 있거나 더 좋은 방향이 있다면 언제든지 말씀해주세요!

2024-11-29 13:36 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/dto/LoginRequestDto.java
>  public class LoginRequestDto {
`/dto` 디렉토리를 `/member`의 하위 디렉토리로 이동하는게 좋다고 생각합니다.

그렇게 생각하는 이유는 member의 dto에 해당하기 때문입니다.

2024-11-29 13:36 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/jwt/SecurityConfig.java
>      public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
SecurityConfig.java를 `/common/config`로 이동하는게 좋을 거 같습니다.

SecurityConfig.java 가 `/jwt` 디렉토리에 포함될 이유가 없다고 생각합니다.

2024-11-29 13:36 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/member/Member.java
>  	@Builder(toBuilder = true)
toBuilder를 사용하신 이유가 뭔가요?

Controller에서 요청 바디를 DTO로 받은 다음 입력 받은 값으로 member를 update하면 어떨까요?

2024-11-30 07:50 UTC, sungryongcho commented
Dto 파일을 보면 Builder 클래스를 새로 만들어서 사용하셨는데 이렇게 하신 이유가 궁금합니다.

생성자를 추가하고 @Builder를 추가해서 사용하지 않은 이유가 뭔가요?
이부분은 제가 찾아보고 공부해보았을 때  Builder 클래스 유연성과 가독성을 높일 수 있고
나중에 확장을 할 때 더 코드 수정이 편하다고 하여서 이렇게 했었습니다.

2024-12-01 12:36 UTC, Daeho-Son requested changes

2024-12-01 12:36 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/member/MemberController.java
> +        if (token == null || !token.startsWith("Bearer ")) {
accessToken은 로그인 등을 제외한 특정 API를 제외한 모든 API를 요청할 때 전부 포함됩니다. 그렇게 되면 룡이 작성한 코드로 인해 모든 Controller의 메서드에서 토큰의 유효성을 검사하는 코드를 추가해야하므로, 잘못된 방식이라고 생각합니다.

인증/인가에 대한 처리는 SpringSecurity를 통해서 해결해야되고, 토큰의 유효성에 관련된 부분에 대한 처리는 JWT Filter에서 처리되어야합니다.

JWT Filter에서 토큰이 있는지 검사하는 과정에서 사용되는 validateToken 메서드에서 이 과정을 처리하면 될 거 같습니다.

2024-12-01 12:36 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/member/MemberController.java
> +        if (introduction == null || introduction.isEmpty()) {
DTO에 관련된 유효성 검사 로직은 DTO에서 처리할 수 있습니다. `@NOT NULL`이나 길이를 검사하는 어노테이션이 있습니다.

제가 생각했을 때 Controller는 요청과 응답을 처리하는 역할을 담당해야하고, 그 외에 비즈니스 로직에 대한 부분은 Service단에서 처리하는 것이 좋다고 생각합니다.

2024-12-01 12:36 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/member/MemberService.java
> +        memberRepository.save(member);
제가 알기로 `@Transactional`을 달았으면 save를 안해줘도 되는 걸로 알고 있습니다.

2024-12-01 12:36 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/auth/AuthController.java
> +        // 비회원용 토큰 생성
비즈니스 로직은 Service단에 있어야한다고 생각합니다.

2024-12-01 12:36 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/auth/NicknameService.java
> +        member.setNickname(newNickname); // 닉네임 수정
NicknameService에는 `@Transactional`이 없는 이유가 있을까요?

2024-12-01 12:36 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/auth/SignupService.java
> +        cacheService.storeAccessToken("ACCESS_TOKEN_" + savedMember.getEmail(), tokenResponse.getAccessToken());
궁금한 점이 있습니다. accessToken 정보를 서버에 저장할 이유가 없다고 생각하는데 캐시로 저장하는 이유가 뭔가요?


추가) 당장에 필요 없는 주석은 지워도 될 거 같습니다.

2024-12-01 12:36 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/member/MemberService.java
> +            member.setProfileImageUrl(null);
Member에 `@Setter`를 통해 모든 값을 변경하게 하는 것보다 Member에 update(MemberProfileImageDto)라는 메서드를 만들고, 그 안에서 필요한 값만 변경하는게 안전할 것 같습니다.

2024-12-01 12:36 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/member/MemberService.java
> +        member.setIntroduction(introduction);
Member에 `@Setter`를 통해 모든 값을 변경하게 하는 것보다 Member에 update(MemberIntroductionUpdateDto)라는 메서드를 만들고, 그 안에서 필요한 값만 변경하는게 안전할 것 같습니다.

이렇게 할 경우, service.updateIntroduction() 메서드의 매개변수를 클라인언트에서 요청 받은 DTO로 설정하면 될 것 같습니다.

2024-12-01 12:36 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/auth/CacheService.java
> +    @Autowired
당장에 사용하지 않는 코드의 주석은 지우는게 좋을 것 같습니다. 나중에 필요할 때 추가해도 된다고 생각합니다.

2024-12-01 12:36 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/auth/CacheService.java
> +    private final Cache<String, String> accessTokenCache;
제가 Cache를 사용하는 부분을 잘 몰라서 질문이 있습니다.

이 코드 방식으로 하면 각 서비스에 필요한 캐시마다 CacheService를 만들고, 그 안에 Cache 타입의 변수에 값을 저장하는 방식으로 진행해야한다고 생각합니다.

CacheConfig 같은 거로 설정하고 MemberService나 AuthService 등 캐시가 필요한 부분에서 캐시를 저장하거나 값을 꺼내오는 방법은 없나요?

2024-12-01 12:42 UTC, Daeho-Son commented
추가 리뷰 남겼습니다.

리뷰의 첫 줄을 보시면 `필수 사항`, `선택 사항`, `질문`로 나눠놨습니다.

2024-12-02 04:16 UTC, sungryongcho commented on src/main/java/com/dayum/dayum_diet/domain/auth/SignupService.java
> +        cacheService.storeAccessToken("ACCESS_TOKEN_" + savedMember.getEmail(), tokenResponse.getAccessToken());
저는 둘다 서버에서 관리해야하는 줄 알고 했었는데 찾아보고 하니 오히려 클라이언트에서 관리하는 것이 더 나은 것 같아서 바꾸겠습니다.

2024-12-02 04:16 UTC, sungryongcho commented on src/main/java/com/dayum/dayum_diet/domain/auth/NicknameService.java
> +        member.setNickname(newNickname); // 닉네임 수정
아 추가하겠습니다.

2024-12-09 10:31 UTC, Daeho-Son requested changes
실행이 안됩니다. validation 라이브러리를 추가하지 않아서 그런 거 같습니다.

2024-12-09 10:31 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/nickname/dto/UpdateNicknameRequestDto.java
> +@Data
**선택**

`@Data` 사용은 지양해야합니다. 대신 필요한 어노테이션을 추가하는 방식으로 구현하면 좋을 것 같습니다.

[참고 자료](https://ddururiiiiiii.tistory.com/369)

2024-12-09 10:31 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/member/dto/MemberIntroductionUpdateDto.java
> +import jakarta.validation.constraints.NotBlank;
**필수**

`/src/main/java/com/dayum/dayum_diet/domain/member/dto/MemberIntroductionUpdateDto.java:3: error: package jakarta.validation.constraints does not exist
import jakarta.validation.constraints.NotBlank;`

에러가 발생합니다. 혹시 `build.gradle`에 추가해야하는 라이브러리가 있나요?

2024-12-09 10:33 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/member/dto/MemberIntroductionUpdateDto.java
> +import jakarta.validation.constraints.NotBlank;
`org.springframework.boot:spring-boot-starter-validation` 를 추가해야할 것 같습니다.

2024-12-11 05:56 UTC, Daeho-Son requested changes
@sungryongcho 

추가적으로 회원 가입, 로그인 로직이 어떻게 되는 건지 잘 모르겠습니다.


회원가입 로직에 관한 이야기입니다.
닉네임, 한 줄 소개, 프로필 이미지만으로 회원가입이 되는 것으로 보이는데 iOS에서 보내준 이메일과 토큰을 검증하고 그걸로 회원가입을 하는게 아닌가요?

로그인(비회원 로그인 포함)에 관한 이야기입니다.
요청에 이메일이 포함되어 있는데 이메일만 있으면 로그인이 되도록 이야기가 된 건가요?

2024-12-11 05:56 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/nickname/NicknameController.java
> +    @PutMapping("/set")
**필수**

`/random`, `/check`와 달리 유저의 닉네임을 변경하는 코드라면 Member에 포함되어야 한다고 생각합니다.

그리고 `/set`은 REST 규칙에 맞지 않는다고 생각하고, `PUT /member/nickname`으로도 그 뜻을 유추할 수 있지 않을까 싶습니다.

2024-12-11 05:56 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/nickname/NicknameController.java
> +    public ResponseEntity<?> checkNickname(@RequestBody Map<String, String> request) {
**선택**

`Map<String, String>` 대신 DTO로 통일하는게 좋을 것 같습니다.

2024-12-11 05:56 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/auth/AuthController.java
> +    public ResponseEntity<TokenResponseDto> signup(@RequestBody Map<String, Object> request) {
**선택**

`Map<String, Object>` 대신 DTO로 통일하는게 좋을 것 같습니다.

2024-12-11 05:56 UTC, Daeho-Son commented on src/main/java/com/dayum/dayum_diet/domain/nickname/NicknameController.java
> +    @PutMapping("/set")
**필수**

UpdateNicknameRequestDto에 email을 담아서 요청받아올 이유가 없다고 생각합니다.
요청 시 같이 담겨있는 access token에서 내 닉네임을 변경하는 방식으로 하지 않을 경우, 다른 사람의 이메일로 요청을 보내서 닉네임을 변경할 가능성이 있어 보입니다.

2024-12-22 13:24 UTC, Daeho-Son approved these changes

2024-12-22 13:26 UTC, merged